baseURL = "https://mvstudios.us"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
themesDir = "../.."
title = "Mountain View Studios"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[menu.main]]
name = "portfolio"
url = "#portfolio"
weight = 2
[[menu.main]]
name = "services"
url = "#services"
weight = 1
[[menu.main]]
name = "contact"
url = "#contact"
weight = 3
[params]
author = "Themefisher"
description = "Mountain View Studios Official Website"
google_analytics_id = "UA-195898563-1"
logo = "/images/no-backgroun-compressed.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "/images/no-backgroun-compressed-1.png"
[[params.social]]
icon = "ti-instagram"
link = "https://www.instagram.com/mt.view_official/"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/MtViewStudios"
